FROM mysql:5.7

# RUN mysql -e "CREATE DATABASE hants_test;";

# RUN chmod +x /tmp/mysql-config.sh && ./tmp/mysql-config.sh

# RUN /bin/bash -c "/usr/bin/mysqld_safe --skip-grant-tables &" && \ mysql -u root -e "CREATE DATABASE hants_test;" 

# CMD ["/tmp/mysql-config.sh"]
